XrpSolutions/Controllers/DebtorsMastersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XrpSolutions.Models;

namespace XrpSolutions.Controllers
{
    public class DebtorsMastersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DebtorsMasters
        public ActionResult Index(string searchName)
        {
            return View(db.DebtorsMasters.Where(x=>x.Address1.Contains(searchName)|| searchName==null).ToList());
        }

        // GET: DebtorsMasters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DebtorsMaster debtorsMaster = db.DebtorsMasters.Find(id);
            if (debtorsMaster == null)
            {
                return HttpNotFound();
            }
            return View(debtorsMaster);
        }
       //This is where we specify the highest and lowest functionality
        public ActionResult HigestDebtor()
        {
            var high = db.DebtorsMasters.OrderByDescending(x => x.Balance).Take(1);
            return View(high);
        }

        public ActionResult LowestDebtor()
        {
            var low = db.DebtorsMasters.OrderBy(x => x.Balance).Take(1);
            return View(low);
        }
        // GET: DebtorsMasters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DebtorsMasters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DebtorId,AccountCode,Address1,Address2,Address3,CostYearToDate,salesYearToDate,Balance")] DebtorsMaster debtorsMaster)
        {
            if (ModelState.IsValid)
            {

                debtorsMaster.Balance = debtorsMaster.CalcBalance();
                db.DebtorsMasters.Add(debtorsMaster);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(debtorsMaster);
        }

        // GET: DebtorsMasters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DebtorsMaster debtorsMaster = db.DebtorsMasters.Find(id);
            if (debtorsMaster == null)
            {
                return HttpNotFound();
            }
            return View(debtorsMaster);
        }

        // POST: DebtorsMasters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DebtorId,AccountCode,Address1,Address2,Address3,CostYearToDate,salesYearToDate,Balance")] DebtorsMaster debtorsMaster)
        {
            if (ModelState.IsValid)
            {
                db.Entry(debtorsMaster).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(debtorsMaster);
        }

        // GET: DebtorsMasters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DebtorsMaster debtorsMaster = db.DebtorsMasters.Find(id);
            if (debtorsMaster == null)
            {
                return HttpNotFound();
            }
            return View(debtorsMaster);
        }

        // POST: DebtorsMasters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DebtorsMaster debtorsMaster = db.DebtorsMasters.Find(id);
            db.DebtorsMasters.Remove(debtorsMaster);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

XrpSolutions/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->


    <link rel="stylesheet" href="~/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link href="~/assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/assets/libs/css/style.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/fontawesome/css/fontawesome-all.css">
    <link rel="stylesheet" href="~/assets/vendor/charts/chartist-bundle/chartist.css">
    <link rel="stylesheet" href="~/assets/vendor/charts/morris-bundle/morris.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendor/charts/c3charts/c3.css">
    <link rel="stylesheet" href="~/assets/vendor/fonts/flag-icon-css/flag-icon.min.css">
    <title>XRP SOLUTION</title>



</head>
<body>
    <!-- ============================================================== -->
    <!-- main wrapper -->
    <!-- ============================================================== -->
    <div class="dashboard-main-wrapper">
        <!-- ============================================================== -->
        <!-- navbar -->
        <!-- ============================================================== -->
        <div class="dashboard-header">
            <nav class="navbar navbar-expand-lg bg-white fixed-top">
                <a class="navbar-brand" href="Home/Index">XRP SOLUTION</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto navbar-right-top"></ul>
                </div>
            </nav>
        </div>
        <!-- ============================================================== -->
        <!-- end navbar -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- left sidebar -->
        <!-- ============================================================== -->
        <div class="nav-left-sidebar sidebar-dark">
            <div class="menu-list">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav flex-column">
                            <li class="nav-divider">
                                Features
                            </li>
                            <li class="nav-item ">
                                <a class="nav-link active" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1" aria-controls="submenu-1"><i class="fa fa-fw fa-user-circle"></i>HOME <span class="badge badge-success">6</span></a>
                                <div id="submenu-1" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-1-2" aria-controls="submenu-1-2">Dashboard</a>
                                            <div id="submenu-1-2" class="collapse submenu" style="">
                                                <ul class="nav flex-column">
                                                    <li class="nav-item">
                                                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home Page</a>
                                                    </li>
                                                    <li class="nav-item">
                                                        <a class="nav-link" href="@Url.Action("About", "Home")">About</a>
                                                    </li>

                                                </ul>
                                            </div>
                                        </li>

                                    </ul>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-2" aria-controls="submenu-2"><i class="fa fa-fw fa-rocket"></i>Debtors</a>
                                <div id="submenu-2" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Create", "DEBTORSMASTERS")">Add Debtor<span class="badge badge-secondary">Add Debtor</span></a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "DebtorsMasters")">Debtors List</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Create", "DEBTORTRANSACTIONFILES")">Add Debtors Transactions</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "DEBTORTRANSACTIONFILES")">Debtors Transactions List</a>
                                        </li>

                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item ">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-4" aria-controls="submenu-4"><i class="fab fa-fw fa-wpforms"></i>Invoice Header</a>
                                <div id="submenu-4" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Create", "INVOICEHEADERS")"> Add invoice Header</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "INVOICEHEADERS")"> Invoice Header List</a>
                                        </li>

                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-3" aria-controls="submenu-3"><i class="fas fa-fw fa-chart-pie"></i>Invoice Details</a>
                                <div id="submenu-3" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Create", "INVOICEDETAILS")">Add Invoice Detail</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "INVOICEDETAILS")">Invoice Detials List</a>
                                        </li>

                                    </ul>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-5" aria-controls="submenu-5"><i class="fas fa-fw fa-table"></i>Stock Master File</a>
                                <div id="submenu-5" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Create", "STOCKMASTERS")">Add Stock Master</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "STOCKMASTERS")">Stock Master Lists</a>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#" data-toggle="collapse" aria-expanded="false" data-target="#submenu-6" aria-controls="submenu-6"><i class="fas fa-fw fa-chart-pie"></i>Stock Transaction Files Details</a>
                                <div id="submenu-6" class="collapse submenu" style="">
                                    <ul class="nav flex-column">
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Create", "STOCKTRANSACTIONFILES")">Add Sotck Transaction</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="@Url.Action("Index", "STOCKTRANSACTIONFILES")">Sotck Transaction Lits</a>
                                        </li>

                                    </ul>
                                </div>
                            </li>


                        </ul>
                </div>
            </nav>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- end left sidebar -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- wrapper  -->
    <!-- ============================================================== -->
    <div class="dashboard-wrapper">
        <div class="dashboard-ecommerce">
            <div class="container-fluid dashboard-content ">
                @RenderBody()
            </div>
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- end footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- end wrapper  -->
        <!-- ============================================================== -->
    </div>

    <!-- ============================================================== -->
    <!-- end main wrapper  -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->
    <!-- jquery 3.3.1 -->
    <script src="~/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <!-- bootstap bundle js -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="~/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <!-- main js -->
    <script src="~/assets/libs/js/main-js.js"></script>
    <!-- chart chartist js -->
    <script src="~/assets/vendor/charts/chartist-bundle/chartist.min.js"></script>
    <!-- sparkline js -->
    <script src="~/assets/vendor/charts/sparkline/jquery.sparkline.js"></script>
    <!-- morris js -->
    <script src="~/assets/vendor/charts/morris-bundle/raphael.min.js"></script>
    <script src="~/assets/vendor/charts/morris-bundle/morris.js"></script>
    <!-- chart c3 js -->
    <script src="~/assets/vendor/charts/c3charts/c3.min.js"></script>
    <script src="~/assets/vendor/charts/c3charts/d3-5.4.0.min.js"></script>
    <script src="~/assets/vendor/charts/c3charts/C3chartjs.js"></script>
    <script src="~/assets/libs/js/dashboard-ecommerce.js"></script>
</body>

</html>
@RenderSection("scripts", required: false)